import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Spacer from '../components/Spacer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>One Door Workshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Spacer bottom="1rem">
          <h1>React Survey</h1>
        </Spacer>
        <h2>Working with One Door</h2>
      </Header>

      <main></main>
      <Footer />
    </div>
  )
}

export default Home
